In [1]:
pip install pandas psycopg2

Requirement already satisfied: pandas in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: psycopg2 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (2.9.10)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\dusty\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~etuptools (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~otebook (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~otebook (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~otebook (C:\Users\Dusty\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
csv_file1 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Pickup Five Cities Datasets\pickup_hz.csv'
csv_file2 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Pickup Five Cities Datasets\pickup_yt.csv'
csv_file3 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Pickup Five Cities Datasets\pickup_sh.csv'
csv_file4 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Pickup Five Cities Datasets\pickup_cq.csv'
csv_file5 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Pickup Five Cities Datasets\pickup_jl.csv'

csv_files = [csv_file1,csv_file2,csv_file3,csv_file4,csv_file5]

# Load all CSV files into dataframes
dfs = [pd.read_csv(file) for file in csv_files]

# Merge all dataframes into one
df_combined_pickup = pd.concat(dfs, ignore_index=True)

In [4]:
df_combined_pickup.sample(10)

,order_id,region_id,city,courier_id,accept_time,time_window_start,time_window_end,lng,lat,aoi_id,aoi_type,pickup_time,pickup_gps_time,pickup_gps_lng,pickup_gps_lat,accept_gps_time,accept_gps_lng,accept_gps_lat,ds
4374379,4411159,47,Shanghai,2269,07-23 07:39:00,07-23 09:00:00,07-23 11:00:00,121.47630,31.27282,22730,1,07-23 09:17:00,07-23 09:17:00,121.47683,31.27224,NaN,NaN,NaN,723
5885333,4663415,11,Jilin,10779,09-13 13:59:00,09-13 13:59:00,09-13 15:59:00,127.33223,43.71893,3512,1,09-13 14:19:00,09-13 14:19:00,127.33176,43.71971,09-13 13:58:00,127.33384,43.72207,913
1489934,2027484,80,Hangzhou,13034,07-26 08:22:00,07-26 09:00:00,07-26 11:00:00,119.92886,30.05648,7311,1,07-26 10:48:00,07-26 10:48:00,119.92903,30.05671,NaN,NaN,NaN,726
1846797,4944244,93,Hangzhou,4097,09-24 07:16:00,09-24 09:00:00,09-24 11:00:00,120.02197,30.27295,9,1,09-24 08:26:00,NaN,NaN,NaN,NaN,NaN,NaN,924
2226043,2621772,102,Yantai,15472,10-29 07:52:00,10-29 09:00:00,10-29 11:00:00,120.40609,37.36339,7403,7,10-29 10:22:00,10-29 10:22:00,120.40612,37.36320,10-29 07:47:00,120.40233,37.34141,1029
2712126,4608195,116,Yantai,4344,10-07 08:14:00,10-07 09:00:00,10-07 11:00:00,121.13609,37.56989,9279,14,10-07 10:35:00,NaN,NaN,NaN,NaN,NaN,NaN,1007
3617325,2475683,15,Shanghai,3595,10-07 08:54:00,10-07 11:00:00,10-07 13:00:00,121.60051,31.26023,6969,1,10-07 09:56:00,10-07 09:56:00,121.60074,31.26001,10-07 08:54:00,121.59867,31.25763,1007
1695171,4419543,84,Hangzhou,857,09-22 12:37:00,09-22 13:00:00,09-22 15:00:00,120.15232,30.31035,18509,1,09-22 14:33:00,09-22 14:32:00,120.15185,30.31023,NaN,NaN,NaN,922
705272,2278937,48,Hangzhou,8315,07-19 10:01:00,07-23 17:00:00,07-23 19:00:00,120.27751,30.43363,13326,1,07-23 17:45:00,07-23 17:45:00,120.27804,30.43367,NaN,NaN,NaN,723
2353853,2712180,106,Yantai,11848,08-21 07:44:00,08-21 09:00:00,08-21 11:00:00,121.47814,37.44970,10206,1,08-21 10:50:00,08-21 10:50:00,121.47678,37.45036,08-21 07:43:00,121.48578,37.42889,821

In [5]:
print(f"Total records after merge: {df_combined_pickup.shape[0]}")

Total records after merge: 6136147

In [6]:
df_combined_pickup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6136147 entries, 0 to 6136146
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   region_id          int64
 2   city               object
 3   courier_id         int64
 4   accept_time        object
 5   time_window_start  object
 6   time_window_end    object
 7   lng                float64
 8   lat                float64
 9   aoi_id             int64
 10  aoi_type           int64
 11  pickup_time        object
 12  pickup_gps_time    object
 13  pickup_gps_lng     float64
 14  pickup_gps_lat     float64
 15  accept_gps_time    object
 16  accept_gps_lng     float64
 17  accept_gps_lat     float64
 18  ds                 int64
dtypes: float64(6), int64(6), object(7)
memory usage: 889.5+ MB

In [7]:
df_combined_pickup.to_csv(r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\pickup_data.csv',index = False)
print(f"Cleaned Pickup data saved ")

Cleaned Pickup data saved

In [9]:
csv_file6 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Delivery Five Cities Datasets\delivery_hz.csv'
csv_file7 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Delivery Five Cities Datasets\delivery_yt.csv'
csv_file8 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Delivery Five Cities Datasets\delivery_sh.csv'
csv_file9 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Delivery Five Cities Datasets\delivery_cq.csv'
csv_file10 = r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\Delivery Five Cities Datasets\delivery_jl.csv'

csv_files_delivery = [csv_file6,csv_file7,csv_file8,csv_file9,csv_file10]

# Load all CSV files into dataframes
dfs_delivery = [pd.read_csv(file_delivery) for file_delivery in csv_files_delivery]

# Merge all dataframes into one
df_combined_delivery = pd.concat(dfs_delivery, ignore_index=True)

In [10]:
df_combined_delivery.sample(10)

,order_id,region_id,city,courier_id,lng,lat,aoi_id,aoi_type,accept_time,accept_gps_time,accept_gps_lng,accept_gps_lat,delivery_time,delivery_gps_time,delivery_gps_lng,delivery_gps_lat,ds
3345740,1950407,78,Shanghai,423,121.60003,31.18674,43461,4,08-09 08:13:00,08-09 08:13:00,121.63157,31.17534,08-09 11:35:00,08-09 11:35:00,121.59926,31.18619,809
1693154,253294,120,Hangzhou,2868,120.28563,30.29809,18837,1,05-24 07:37:00,05-24 07:37:00,120.27443,30.31324,05-24 09:21:00,05-24 09:21:00,120.28663,30.29702,524
1897476,626497,102,Yantai,27,121.25758,37.51011,41399,1,09-23 10:13:00,09-23 10:13:00,121.28276,37.48183,09-23 19:00:00,09-23 19:00:00,121.26260,37.50983,923
3254246,346849,73,Shanghai,3992,121.29279,31.20423,52566,1,10-18 14:25:00,10-18 14:25:00,121.29880,31.20770,10-18 16:17:00,10-18 16:17:00,121.29281,31.20420,1018
1546819,613651,114,Hangzhou,4122,120.16330,30.25469,2755,7,08-23 18:53:00,08-23 18:53:00,120.17088,30.24213,08-23 20:05:00,08-23 20:05:00,120.16324,30.25468,823
2948420,1266706,54,Shanghai,2567,121.20530,31.12851,5055,1,08-23 08:27:00,08-23 08:27:00,121.19731,31.12637,08-23 10:58:00,08-23 10:58:00,121.20565,31.12842,823
2189898,3066087,6,Shanghai,1996,121.37160,31.30733,49846,1,09-10 10:08:00,09-10 10:08:00,121.36941,31.31677,09-10 10:22:00,09-10 10:22:00,121.37167,31.30735,910
4276215,1901781,153,Chongqing,997,106.55261,29.63404,35346,1,07-05 13:58:00,07-05 13:58:00,106.56435,29.67275,07-05 16:16:00,07-05 16:16:00,106.55038,29.63330,705
1740231,1398957,121,Hangzhou,3517,120.11302,30.27888,18944,1,09-29 15:34:00,09-29 15:34:00,120.10977,30.27759,09-29 16:52:00,09-29 16:52:00,120.11270,30.27907,929
2483771,2129377,25,Shanghai,655,121.55844,31.19402,29117,7,09-02 10:09:00,09-02 10:09:00,121.56014,31.18909,09-02 11:24:00,09-02 11:24:00,121.55792,31.19380,902

In [11]:
print(f"Total records after merge: {df_combined_delivery.shape[0]}")

Total records after merge: 4514661

In [12]:
df_combined_delivery.to_csv(r'C:\Users\Dusty\Downloads\Internship\Last-Mile-Delivery-Delays-and-Route-Optimization\data\delivery_data.csv',index = False)
print(f"Cleaned Delivery data saved ")

Cleaned Delivery data saved